apiVersion: v1
kind: Service

metadata:
  name: hostname-loadbalancer
  namespace: project-7

spec:
  type: LoadBalancer

  selector:
    app: hostname-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80