apiVersion: v1
kind: Service

metadata:
  name: hostname-nodeport
  namespace: project-7

spec:
  type: NodePort

  selector:
    app: hostname-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080